[package]
name = "anti-collision"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "two-ip-ru"
path = "src/main.rs"

[dependencies]

reqwest = { version = "0.11", features = ["blocking", "json", "stream"] }
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
chrono = "0.4"


